### ISSUE TITLE
dual monitor cant work.

### ISSUE THREAD

**Issue by gubasbaa** [picopock/hackintosh_ASUS_ROG_Z390#6]
**Describe the bug**
dual monitor cant work.

**To Reproduce**
1. login success
2. wait a few seconds
3. it black screen
4. cant do anything 

**Expected behavior**
fix to use dual monitor 

**Screenshots**
![ภาพ](https://user-images.githubusercontent.com/68296096/102633587-34f62580-4183-11eb-9474-0a3fe2316e7c.png)

**Version (please complete the following information):**
 - OC: [0.6.4]
 - BIOS: [1704]
 - MacOS [11.0.1]

**Additional context**
use affter login a few second. and cant work.
DP is black screen and HDMI screen crash.
Thank you for help and make efi for work perfectly.

**Comment by xinsui01** [comment]
@gubasbaa 
I only have one monitor and can't solve this problem at present.

Some information：
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/

**Comment by Tiku96** [comment]
Hi,

the two monitors work for me, but I always have to turn the monitor connected to the display port off and on again

**Comment by picopock** [comment]
@gubasbaa @Tiku96 I find some available framebuffer patch, and will update config file later.

but it always not perfect, the HDMI output screen has a green screen for about 1 second during startup. I've been testing for a few hours and haven't found any problems, except for this.
